version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.0
    container_name: postgis
    environment:
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  web:
    build: .
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgis_data:
